- name: install nginx using the ansible
  hosts: ram
  become: true
  tasks:
    - name: update cache
      apt:
        update_cache: yes
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: start nginx
      service:
        name: nginx
        state: started
